[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
crypto = { version = "0.1.0", path = "../crypto" }
domain = { version = "0.1.0", path = "../domain" }
error = { version = "0.1.0", path = "../error" }
secure-string = "0.3.0"
